# General config
root        :
weights     :
data        :
model       :
fullname    :
save_dir    :
device      : 0
epochs      : 1000
steps       :
imgsz       : 512
resize      :
benchmark   :
save_image  :
use_data_dir:
exist_ok    : False
verbose     : True

# Model
load_pretrain: False
beta         : 1

# Training
train_batch_size: 16
val_batch_size  : 8
num_workers     : 5
lr              : 0.0001
weight_decay    : 0.00005
grad_clip_norm  : 0.1
display_iter    : 10
checkpoint_iter : 10
