# Basic
hostname    : ~
config      : ~
arch        : "mtfe"
model       : "mtfe"
data        : "lol_v1"
data_dir    : "data/enhance/llie/lol_v1/train/lq"
root        : ~
project     : ~
variant     : ~
fullname    : "mtfe_lol_v1"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/mtfe/mtfe/lol_v1/mtfe_lol_v1.pth"
device      : 0
local_rank  : ~
launcher    : ~
epochs      : 1000
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
load_pretrain   : False
beta            : 1
train_batch_size: 16
val_batch_size  : 8
num_workers     : 5
lr              : 0.0001
weight_decay    : 0.00005
grad_clip_norm  : 0.1
display_iter    : 10
checkpoint_iter : 10
