# Basic
hostname    : ~
config      : ~
arch        : "llunet++"
model       : "llunet++"
data        : "lol_v2_synthetic"
data_dir    : "data/enhance/llie/lol_v2_synthetic/train/lq"
root        : ~
project     : ~
variant     : ~
fullname    : "lunet++_lol_v2_synthetic"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/llunet++/llunet++/lol_v2_synthetic/llunet++_lol_v2_synthetic_best_psnr.pt"
device      : 0
local_rank  : ~
launcher    : ~
epochs      : 100
steps       : ~
imgsz       : 384
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
exist_ok    : False
verbose     : True

# Model Specific
loss_weights: [0.35, 0.10, 0.25, 0.30]
batch_size  : 4
lr          : 0.00001
