# Basic
hostname    : ~
config      : ~
arch        : "zeroig"
model       : "zeroig"
data        : "fusion"
data_dir    : "data/enhance/llie/fusion/test/lq"
root        : ~
project     : ~
variant     : ~
fullname    : "zeroig_fusion"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/zeroig/zeroig/fusion/zeroig_fusion.pt"
device      : ~
local_rank  : ~
launcher    : ~
epochs      : 2001
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
exist_ok    : False
verbose     : True

# Model Specific
seed       : 2
batch_size : 1
num_workers: 0
lr         : 0.0003
