#
#     /\_____/\
#    /  o   o  \
#   ( ==  ^  == )
#    )         (
#   (           )
#  ( (  )   (  ) )
# (__(__)___(__)__)
#
[tool.poetry]
name          = "mon"
version       = "1.2.0"
description   = "MON covers a wide range of research topics in computer vision, machine learning, and deep learning."
license       = "MIT"
authors       = [
    "Long H. Pham <longpham3105@gmail.com>",
]
maintainers   = [
    "Long H. Pham <longpham3105@gmail.com>",
]
readme        = "README.md"
repository    = "https://github.com/phlong3105/one"
documentation = "https://github.com/phlong3105/one/docs"
keywords      = [
    "computer vision",
    "image processing",
    "deep learning",
    "research",
]
classifiers   = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
]
packages = [
    { include="mon",  from="src"     },
    { include="supr", from="src/app" },
    { include="ug2",  from="src/app" },
]
include  = [
    "CHANGELOG.md",
    "GUIDELINE.md",
    "README.md",
    "install.sh",
    "linux.yaml",
    "mac.yaml",
]
exclude  = []

[tool.poetry.dependencies]
python                = ">=3.10, <3.12"
# # CUDA
# pynvml                = "*"
# # Documentation
# markdown              = "*"
# mkdocs                = "*"
# mkdocstrings          = "*"
# mkdocs-material       = "*"
# sphinx                = "*"
# sphinx-paramlinks     = "*"
# # Image
# albumentations        = "*"
# ffmpeg-python         = "*"
# opencv-python         = "*"
# opencv-contrib-python = "*"
# # Network
# requests              = "*"
# # Plot
# matplotlib            = "*"
# tensorboard           = "*"
# # # PyTorch
# einops                = "*"
# flopco-pytorch        = "*"
# lightning             = ">=1.9.1"
# pytorch-lightning     = ">=1.9.1"
# piqa                  = "*"
# pyiqa                 = "*"
# torch                 = "*"
# torchaudio            = "*"
# torchmetrics          = "*"
# torchvision           = "*"
# # Ray
# ray                   = "*"
# # Scientific
# filterpy              = "*"
# numpy                 = "*"
# scipy                 = "*"
# scikit-learn          = "*"
# # Syntax
# multipledispatch      = "*"
# mypy                  = "*"
# protobuf              = "*"
# pyhumps               = "*"
# PyYAML                = "*"
# sortedcontainers      = "*"
# typing-extensions     = "*"
# validators            = "*"
# xmltodict             = "*"
# # UI
# PyQt6                 = "*"
# rich                  = "*"
# tqdm                  = "*"

[tool.poetry.group.dev]
optional  = true

[tool.poetry.group.dev.dependencies]
mediapipe = "*"
torchfile = "*"

[build-system]
requires      = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
# build-backend = "setuptools.build_meta"
