name    : "convnext-large"
channels: 3
backbone: [
  # [from, number, module,               args(out_channels, ...)]
  [-1,     1,      Conv2dNormActivation, [192, 4, 4, 0, 1, LayerNorm2d, None, 1, True, True]],  # 0 total_stage_blocks = 36
  [-1,     1,      ConvNeXtBlock,        [192, 1e-6, 0.5, 3,  0,  36]],                         # 1
  [-1,     1,      LayerNorm2d,          [192]],                                                # 2
  [-1,     1,      Conv2d,               [384, 2, 2]],                                          # 3
  [-1,     1,      ConvNeXtBlock,        [384, 1e-6, 0.5, 3,  3,  36]],                         # 4
  [-1,     1,      LayerNorm2d,          [384]],                                                # 5
  [-1,     1,      Conv2d,               [768, 2, 2]],                                          # 6
  [-1,     1,      ConvNeXtBlock,        [768, 1e-6, 0.5, 27, 6,  36]],                         # 7
  [-1,     1,      LayerNorm2d,          [768]],                                                # 8
  [-1,     1,      Conv2d,               [1536, 2, 2]],                                         # 9
  [-1,     1,      ConvNeXtBlock,        [1536, 1e-6, 0.5, 3,  33, 36]],                        # 10
  [-1,     1,      AdaptiveAvgPool2d,    [1]],                                                  # 11
]
head    : [
  [-1,     1,      ConvNeXtClassifier,   [1536, LayerNorm2d]],                                  # 12
]
