name    : "densenet161"
channels: 3
backbone: [
  # [from, number, module,            args(out_channels, ...)]
  [-1,     1,      Conv2d,            [96, 7, 2, 3, 1, 1, False]],     # 0
  [-1,     1,      BatchNorm2d,       []],                             # 1
  [-1,     1,      ReLU,              [True]],                         # 2
  [-1,     1,      MaxPool2d,         [3, 2, 1]],                      # 3
  [-1,     1,      DenseBlock,        [96,   48, 6,  4, 0.0, False]],  # 4   c2 = 96   + 48 * 6  = 384
  [-1,     1,      DenseTransition,   [384,  192]],                    # 5   c2 = 384 // 2       = 192
  [-1,     1,      DenseBlock,        [192,  48, 12, 4, 0.0, False]],  # 6   c2 = 192  + 48 * 12 = 768
  [-1,     1,      DenseTransition,   [768,  384]],                    # 7   c2 = 768 // 2       = 384
  [-1,     1,      DenseBlock,        [384,  48, 36, 4, 0.0, False]],  # 8   c2 = 384  + 48 * 36 = 2112
  [-1,     1,      DenseTransition,   [2112, 1056]],                   # 9   c2 = 2112 // 2      = 1056
  [-1,     1,      DenseBlock,        [1056, 48, 24, 4, 0.0, False]],  # 10  c2 = 1056 + 48 * 24 = 2208
  [-1,     1,      BatchNorm2d,       []],                             # 11
  [-1,     1,      AdaptiveAvgPool2d, [1]],                            # 12
]
head    : [
  [-1,     1,      LinearClassifier,  [2208]],                         # 13
]
