name    : "densenet201"
channels: 3
backbone: [
  # [from, number, module,            args(out_channels, ...)]
  [-1,     1,      Conv2d,            [64, 7, 2, 3, 1, 1, False]],     # 0
  [-1,     1,      BatchNorm2d,       []],                             # 1
  [-1,     1,      ReLU,              [True]],                         # 2
  [-1,     1,      MaxPool2d,         [3, 2, 1]],                      # 3
  [-1,     1,      DenseBlock,        [64,   32, 6,  4, 0.0, False]],  # 4   c2 = 64 + 32 * 6   = 256
  [-1,     1,      DenseTransition,   [256,  128]],                    # 5   c2 = 256 // 2      = 128
  [-1,     1,      DenseBlock,        [128,  32, 12, 4, 0.0, False]],  # 6   c2 = 128 + 32 * 12 = 512
  [-1,     1,      DenseTransition,   [512,  256]],                    # 7   c2 = 512 // 2      = 256
  [-1,     1,      DenseBlock,        [256,  32, 48, 4, 0.0, False]],  # 8   c2 = 256 + 32 * 48 = 1792
  [-1,     1,      DenseTransition,   [1792, 896]],                    # 9   c2 = 1792 // 2     = 896
  [-1,     1,      DenseBlock,        [896,  32, 32, 4, 0.0, False]],  # 10  c2 = 896 + 32 * 32 = 1920
  [-1,     1,      BatchNorm2d,       []],                             # 11
  [-1,     1,      AdaptiveAvgPool2d, [1]],                            # 12
]
head    : [
  [-1,     1,      LinearClassifier,  [1920]],                         # 13
]
