# Basic
hostname    : ~
config      : ~
arch        : "zero_didce"
model       : "zero_didce"
data        : "sice_mix"
root        : ~
project     : ~
variant     : ~
fullname    : ~
save_dir    : ~
weights     : ~
device      : 0
local_rank  : -1
launcher    : ~
epochs      : 200
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
exist_ok    : False
verbose     : True

# Model Specific
load_pretrain   : False
train_batch_size: 32
val_batch_size  : 4
num_workers     : 4
lr              : 0.0001
weight_decay    : 0.0001
grad_clip_norm  : 0.1
display_iter    : 10
checkpoint_iter : 10
